### PR TITLE
Submitting Bobae's PS5 (I did what I could do)

### PR DESCRIPTION
**Pull request by bobaekang**
The criterion value for the SMM is so large that it concerns me. Is there anyone else in the same situation?

### CODE REVIEW

**Comment by merubhanot** [comment]
Yeah I had the same thing..

**Comment by olivianatan** [comment]
I got that for some starting values at first, but then once I used the returned values as initial values, the criterion was less than 1.

**Comment by bobaekang** [comment]
@olivianatan That is very impressive. Even with the GMM estimates, my best SMM crit value is still large: 5.7e+15. I feel like this is still understandable because the moments themselves are fairly large. I am really curious how you could get such a low criterion value though,..

**Comment by olivianatan** [comment]
@bobaekang Is it possible you are using simple (ie differences only) error vector (from what I can see, that's the case in your script)? I'm using the errors as a % diff, which likely explains why the sum of squared values is so small.

**Comment by bobaekang** [comment]
@olivianatan Oh, that might be the explanation for what's going on for my criterion value. I'll play with the simple/percent errors. Thank you for the insight!

**Comment by rickecon** [comment]
@olivianatan @bobaekang @merubhanot . In PS5 exercise 1 (the GMM problem), I recommended that you use simple differences. However, there seems to be scaling problem with the moment conditions. This is because the data on consumption and capital were in the millions of units. These were aggregate countrywide data. So the moment values squared were much larger for the two Euler equation conditions than for the two productivity `z_t` process equations. One way to take care of this is to change the moment conditions to the following.

image

Note that those moments are in the same percent change units. It is just that the ratio in the expectation equals 1 rather than zero. The moment conditions for the Euler equations are the same as in the problem set.

image

This should treatment of the productivity equation moments should reduce the units problem in the GMM exercise.

**Comment by rickecon** [comment]
@bobaekang @merubhanot @olivianatan . In PS5, exercise 2 (the SMM problem), you should be using the percent deviation of model moments from data moments as your error function. This should make your criterion values smaller.

**Pull request merged**
